import { Router } from "express";
import ApiKeyRoute from "./ApiKey.route";
import BillRoute from "./Bill.route";
import BookingRoute from "./Booking.route";
import BookingsImageRoute from "./BookingsImage.route";
import DepartmentRoute from "./Department.route";
import DoctorRoute from "./Doctor.route";
import DoctorsInforRoute from "./DoctorsInfor.route";
import EmployeeRoute from "./Employee.route";
import EmployeeInfoRoute from "./EmployeeInfo.route";
import EquipmentRoute from "./Equipment.route";
import EquipmentTypeRoute from "./EquipmentType.route";
import ExaminationCardRoute from "./ExaminationCard.route";
import ExaminationCardsDetailRoute from "./ExaminationCardsDetail.route";
import HourObjectRoute from "./HourObject.route";
import LogRoute from "./Log.route";
import MedicineRoute from "./Medicine.route";
import MedicineDetailRoute from "./MedicineDetail.route";
import MedicineTypeRoute from "./MedicineType.route";
import NotificationRoute from "./Notification.route";
import OperationRoute from "./Operation.route";
import OwnerRoute from "./Owner.route";
import OwnerInfoRoute from "./OwnerInfo.route";
import PatientRoute from "./Patient.route";
import PatientInfoRoute from "./PatientInfo.route";
import PatientTypeRoute from "./PatientType.route";
import PermissionRoute from "./Permission.route";
import PositionRoute from "./Position.route";
import PrescriptionRoute from "./Prescription.route";
import PrescriptionsDetailRoute from "./PrescriptionsDetail.route";
import QualifiedDoctorRoute from "./QualifiedDoctor.route";
import RefreshTokensUseRoute from "./RefreshTokensUse.route";
import ReportRoute from "./Report.route";
import ResultsDiagnosisSubclinicalRoute from "./ResultsDiagnosisSubclinical.route";
import ResultsImageRoute from "./ResultsImage.route";
import RoleRoute from "./Role.route";
import RolePermissionRoute from "./RolePermission.route";
import RoomRoute from "./Room.route";
import SaveExpoPushTokenRoute from "./SaveExpoPushToken.route";
import ScheduleDoctorRoute from "./ScheduleDoctor.route";
import ServiceRoute from "./Service.route";
import ServiceSubclinicalRoute from "./ServiceSubclinical.route";
import ServiceTypeRoute from "./ServiceType.route";
import SessionsCheckupRoute from "./SessionsCheckup.route";
import SpecialistRoute from "./Specialist.route";
import SubclinicalRoute from "./Subclinical.route";
import SubclinicalTypeRoute from "./SubclinicalType.route";
import TokenPairRoute from "./TokenPair.route";
import UnitRoute from "./Unit.route";

const router = Router();

router.use("/api/v1/Logs", LogRoute);
router.use("/api/v1/Permissions", PermissionRoute);
router.use("/api/v1/Roles", RoleRoute);
router.use("/api/v1/RolePermissions", RolePermissionRoute);
router.use("/api/v1/Owners", OwnerRoute);
router.use("/api/v1/OwnerInfos", OwnerInfoRoute);
router.use("/api/v1/PatientTypes", PatientTypeRoute);
router.use("/api/v1/Patients", PatientRoute);
router.use("/api/v1/PatientInfos", PatientInfoRoute);
router.use("/api/v1/Employees", EmployeeRoute);
router.use("/api/v1/EmployeeInfos", EmployeeInfoRoute);
router.use("/api/v1/QualifiedDoctors", QualifiedDoctorRoute);
router.use("/api/v1/Doctors", DoctorRoute);
router.use("/api/v1/DoctorsInfors", DoctorsInforRoute);
router.use("/api/v1/ApiKeys", ApiKeyRoute);
router.use("/api/v1/TokenPairs", TokenPairRoute);
router.use("/api/v1/RefreshTokensUses", RefreshTokensUseRoute);
router.use("/api/v1/Specialists", SpecialistRoute);
router.use("/api/v1/ServiceTypes", ServiceTypeRoute);
router.use("/api/v1/Units", UnitRoute);
router.use("/api/v1/Departments", DepartmentRoute);
router.use("/api/v1/Positions", PositionRoute);
router.use("/api/v1/Operations", OperationRoute);
router.use("/api/v1/SessionsCheckups", SessionsCheckupRoute);
router.use("/api/v1/Services", ServiceRoute);
router.use("/api/v1/SubclinicalTypes", SubclinicalTypeRoute);
router.use("/api/v1/Subclinicals", SubclinicalRoute);
router.use("/api/v1/MedicineTypes", MedicineTypeRoute);
router.use("/api/v1/Medicines", MedicineRoute);
router.use("/api/v1/EquipmentTypes", EquipmentTypeRoute);
router.use("/api/v1/Equipments", EquipmentRoute);
router.use("/api/v1/MedicineDetails", MedicineDetailRoute);
router.use("/api/v1/ScheduleDoctors", ScheduleDoctorRoute);
router.use("/api/v1/HourObjects", HourObjectRoute);
router.use("/api/v1/Bookings", BookingRoute);
router.use("/api/v1/ExaminationCards", ExaminationCardRoute);
router.use("/api/v1/ExaminationCardsDetails", ExaminationCardsDetailRoute);
router.use("/api/v1/Rooms", RoomRoute);
router.use("/api/v1/ServiceSubclinicals", ServiceSubclinicalRoute);
router.use("/api/v1/Bills", BillRoute);
router.use("/api/v1/ResultsDiagnosisSubclinicals", ResultsDiagnosisSubclinicalRoute);
router.use("/api/v1/Prescriptions", PrescriptionRoute);
router.use("/api/v1/PrescriptionsDetails", PrescriptionsDetailRoute);
router.use("/api/v1/BookingsImages", BookingsImageRoute);
router.use("/api/v1/ResultsImages", ResultsImageRoute);
router.use("/api/v1/Notifications", NotificationRoute);
router.use("/api/v1/SaveExpoPushTokens", SaveExpoPushTokenRoute);
router.use("/api/v1/Reports", ReportRoute);

export default router;
